//! Root/control metadata, epoch, and placement-map codecs.

use std::collections::{BTreeMap, HashMap};

use super::assign::{SPIRE_FIRST_LOCAL_VEC_SEQ, SPIRE_FIRST_PID};
use crate::storage::page::{ItemPointer, ITEM_POINTER_BYTES};

pub(super) const SPIRE_LOCAL_NODE_ID: u32 = 0;
pub(super) const SPIRE_SINGLE_LOCAL_STORE_ID: u32 = 0;
pub(super) const SPIRE_DEFAULT_LOCAL_STORE_GENERATION: u64 = 0;
pub(super) const SPIRE_MIN_EPOCH_RETENTION_SECS: u32 = 10 * 60;
pub(super) const SPIRE_FAILED_EPOCH_RETENTION_SECS: u32 = 60 * 60;
pub(super) const SPIRE_MAX_RETAINED_RETIRED_EPOCHS: u16 = 2;

pub const SPIRE_META_FORMAT_VERSION: u16 = 1;
const META_FORMAT_VERSION: u16 = SPIRE_META_FORMAT_VERSION;
pub const SPIRE_ROOT_CONTROL_MAGIC: u32 = 0x4352_5345; // "ESRC" as little-endian bytes.
const ROOT_CONTROL_MAGIC: u32 = SPIRE_ROOT_CONTROL_MAGIC;
const ROOT_CONTROL_STATE_BYTES: usize = 4 + 2 + 2 + 8 + 8 + 8 + ITEM_POINTER_BYTES * 4;
pub const SPIRE_LOCAL_STORE_CONFIG_MAGIC: u32 = 0x534c_5345; // "ESLS" as little-endian bytes.
const LOCAL_STORE_CONFIG_MAGIC: u32 = SPIRE_LOCAL_STORE_CONFIG_MAGIC;
pub const SPIRE_LOCAL_STORE_CONFIG_HEADER_BYTES: usize = 4 + 2 + 2 + 8 + 4;
pub const SPIRE_LOCAL_STORE_CONFIG_MAGIC_OFFSET: usize = 0;
pub const SPIRE_LOCAL_STORE_CONFIG_FORMAT_VERSION_OFFSET: usize = 4;
pub const SPIRE_LOCAL_STORE_CONFIG_RESERVED_OFFSET: usize = 6;
pub const SPIRE_LOCAL_STORE_CONFIG_GENERATION_OFFSET: usize = 8;
pub const SPIRE_LOCAL_STORE_CONFIG_STORE_COUNT_OFFSET: usize = 16;
pub const SPIRE_LOCAL_STORE_DESCRIPTOR_BYTES: usize = 4 + 4 + 4 + 1 + 3;
pub const SPIRE_LOCAL_STORE_DESCRIPTOR_LOCAL_STORE_ID_OFFSET: usize = 0;
pub const SPIRE_LOCAL_STORE_DESCRIPTOR_STORE_RELID_OFFSET: usize = 4;
pub const SPIRE_LOCAL_STORE_DESCRIPTOR_TABLESPACE_OID_OFFSET: usize = 8;
pub const SPIRE_LOCAL_STORE_DESCRIPTOR_STATE_OFFSET: usize = 12;
pub const SPIRE_LOCAL_STORE_DESCRIPTOR_RESERVED_OFFSET: usize = 13;
const LOCAL_STORE_CONFIG_HEADER_BYTES: usize = SPIRE_LOCAL_STORE_CONFIG_HEADER_BYTES;
const LOCAL_STORE_DESCRIPTOR_BYTES: usize = SPIRE_LOCAL_STORE_DESCRIPTOR_BYTES;
pub const SPIRE_PLACEMENT_DIRECTORY_MAGIC: u32 = 0x4450_5345; // "ESPD" as little-endian bytes.
const PLACEMENT_DIRECTORY_MAGIC: u32 = SPIRE_PLACEMENT_DIRECTORY_MAGIC;
pub const SPIRE_PLACEMENT_DIRECTORY_HEADER_BYTES: usize = 4 + 2 + 2 + 8 + 4;
pub const SPIRE_PLACEMENT_DIRECTORY_MAGIC_OFFSET: usize = 0;
pub const SPIRE_PLACEMENT_DIRECTORY_FORMAT_VERSION_OFFSET: usize = 4;
pub const SPIRE_PLACEMENT_DIRECTORY_RESERVED_OFFSET: usize = 6;
pub const SPIRE_PLACEMENT_DIRECTORY_EPOCH_OFFSET: usize = 8;
pub const SPIRE_PLACEMENT_DIRECTORY_ENTRY_COUNT_OFFSET: usize = 16;
const PLACEMENT_DIRECTORY_HEADER_BYTES: usize = SPIRE_PLACEMENT_DIRECTORY_HEADER_BYTES;
pub const SPIRE_OBJECT_MANIFEST_MAGIC: u32 = 0x4d4f_5345; // "ESOM" as little-endian bytes.
const OBJECT_MANIFEST_MAGIC: u32 = SPIRE_OBJECT_MANIFEST_MAGIC;
pub const SPIRE_OBJECT_MANIFEST_HEADER_BYTES: usize = 4 + 2 + 2 + 8 + 4;
pub const SPIRE_OBJECT_MANIFEST_MAGIC_OFFSET: usize = 0;
pub const SPIRE_OBJECT_MANIFEST_FORMAT_VERSION_OFFSET: usize = 4;
pub const SPIRE_OBJECT_MANIFEST_RESERVED_OFFSET: usize = 6;
pub const SPIRE_OBJECT_MANIFEST_EPOCH_OFFSET: usize = 8;
pub const SPIRE_OBJECT_MANIFEST_ENTRY_COUNT_OFFSET: usize = 16;
const OBJECT_MANIFEST_HEADER_BYTES: usize = SPIRE_OBJECT_MANIFEST_HEADER_BYTES;
pub const SPIRE_EPOCH_MANIFEST_MAGIC: u32 = 0x454d_5345; // "ESME" as little-endian bytes.
const EPOCH_MANIFEST_MAGIC: u32 = SPIRE_EPOCH_MANIFEST_MAGIC;
pub const SPIRE_PLACEMENT_ENTRY_BYTES: usize =
    2 + 1 + 1 + 8 + 8 + 4 + 4 + 4 + 8 + ITEM_POINTER_BYTES + 4;
pub const SPIRE_PLACEMENT_ENTRY_FORMAT_VERSION_OFFSET: usize = 0;
pub const SPIRE_PLACEMENT_ENTRY_STATE_OFFSET: usize = 2;
pub const SPIRE_PLACEMENT_ENTRY_RESERVED_OFFSET: usize = 3;
pub const SPIRE_PLACEMENT_ENTRY_EPOCH_OFFSET: usize = 4;
pub const SPIRE_PLACEMENT_ENTRY_PID_OFFSET: usize = 12;
pub const SPIRE_PLACEMENT_ENTRY_NODE_ID_OFFSET: usize = 20;
pub const SPIRE_PLACEMENT_ENTRY_LOCAL_STORE_ID_OFFSET: usize = 24;
pub const SPIRE_PLACEMENT_ENTRY_STORE_RELID_OFFSET: usize = 28;
pub const SPIRE_PLACEMENT_ENTRY_OBJECT_VERSION_OFFSET: usize = 32;
pub const SPIRE_PLACEMENT_ENTRY_OBJECT_TID_OFFSET: usize = 40;
pub const SPIRE_PLACEMENT_ENTRY_OBJECT_BYTES_OFFSET: usize = 46;
const PLACEMENT_ENTRY_BYTES: usize = SPIRE_PLACEMENT_ENTRY_BYTES;
pub const SPIRE_EPOCH_MANIFEST_BYTES: usize = 4 + 2 + 1 + 1 + 8 + 8 + 8 + 8;
pub const SPIRE_EPOCH_MANIFEST_MAGIC_OFFSET: usize = 0;
pub const SPIRE_EPOCH_MANIFEST_FORMAT_VERSION_OFFSET: usize = 4;
pub const SPIRE_EPOCH_MANIFEST_STATE_OFFSET: usize = 6;
pub const SPIRE_EPOCH_MANIFEST_CONSISTENCY_MODE_OFFSET: usize = 7;
pub const SPIRE_EPOCH_MANIFEST_EPOCH_OFFSET: usize = 8;
pub const SPIRE_EPOCH_MANIFEST_PUBLISHED_AT_MICROS_OFFSET: usize = 16;
pub const SPIRE_EPOCH_MANIFEST_RETAIN_UNTIL_MICROS_OFFSET: usize = 24;
pub const SPIRE_EPOCH_MANIFEST_ACTIVE_QUERY_COUNT_OFFSET: usize = 32;
const EPOCH_MANIFEST_BYTES: usize = SPIRE_EPOCH_MANIFEST_BYTES;
pub const SPIRE_MANIFEST_ENTRY_BYTES: usize = 2 + 2 + 8 + 8 + 8 + ITEM_POINTER_BYTES;
pub const SPIRE_MANIFEST_ENTRY_FORMAT_VERSION_OFFSET: usize = 0;
pub const SPIRE_MANIFEST_ENTRY_RESERVED_OFFSET: usize = 2;
pub const SPIRE_MANIFEST_ENTRY_EPOCH_OFFSET: usize = 4;
pub const SPIRE_MANIFEST_ENTRY_PID_OFFSET: usize = 12;
pub const SPIRE_MANIFEST_ENTRY_OBJECT_VERSION_OFFSET: usize = 20;
pub const SPIRE_MANIFEST_ENTRY_PLACEMENT_TID_OFFSET: usize = 28;
const MANIFEST_ENTRY_BYTES: usize = SPIRE_MANIFEST_ENTRY_BYTES;

include!("meta/root_control.rs");
include!("meta/states.rs");
include!("meta/local_store.rs");
include!("meta/placement.rs");
include!("meta/placement_directory.rs");
include!("meta/epoch.rs");
include!("meta/object_manifest.rs");
include!("meta/snapshot.rs");
include!("meta/tests.rs");
