pub(crate) unsafe fn remote_search_production_consistency_policy_summary_row(
    index_relation: pg_sys::Relation,
    requested_epoch: u64,
    consistency_mode_source: &'static str,
    consistency_mode: &str,
) -> SpireRemoteProductionConsistencyPolicySummaryRow {
    let result = (|| -> Result<SpireRemoteProductionConsistencyPolicySummaryRow, String> {
        if requested_epoch == 0 {
            return Err(
                "ec_spire remote search production consistency policy requested_epoch must be greater than 0"
                    .to_owned(),
            );
        }
        let requested_consistency_mode = parse_remote_search_consistency_mode(consistency_mode)?;
        let requested_consistency_mode = consistency_mode_name(requested_consistency_mode);
        let root_control = unsafe { page::read_root_control_page(index_relation) };
        let (epoch_manifest, _, _) =
            unsafe { load_relation_epoch_manifests_for_coordinator_fanout(index_relation, root_control)? };
        let active_consistency_mode = consistency_mode_name(epoch_manifest.consistency_mode);

        let (
            status,
            failure_category,
            failure_action,
            recommendation,
        ) = if root_control.active_epoch != requested_epoch {
            (
                SPIRE_REMOTE_PRODUCTION_REQUESTED_EPOCH_MISMATCH,
                SPIRE_REMOTE_PRODUCTION_REQUESTED_EPOCH_MISMATCH,
                "fail_closed",
                "request the active epoch before planning production remote fanout",
            )
        } else if active_consistency_mode != requested_consistency_mode {
            (
                SPIRE_REMOTE_STATUS_CONSISTENCY_MODE_MISMATCH,
                SPIRE_REMOTE_STATUS_CONSISTENCY_MODE_MISMATCH,
                "fail_closed",
                "publish a degraded-capable epoch or run the query with the active epoch policy",
            )
        } else {
            (
                SPIRE_REMOTE_STATUS_READY,
                SPIRE_REMOTE_NONE,
                SPIRE_REMOTE_NONE,
                "consistency policy is ready for production dispatch planning",
            )
        };

        Ok(SpireRemoteProductionConsistencyPolicySummaryRow {
            requested_epoch,
            active_epoch: root_control.active_epoch,
            consistency_mode_source,
            requested_consistency_mode,
            active_consistency_mode,
            status,
            failure_category,
            failure_action,
            next_executor_step: if status == SPIRE_REMOTE_STATUS_READY {
                SPIRE_REMOTE_EXECUTOR_STEP_BUDGET
            } else {
                SPIRE_REMOTE_EXECUTOR_STEP_CONSISTENCY_POLICY
            },
            recommendation,
        })
    })();
    result.unwrap_or_else(|e| pgrx::error!("{e}"))
}

pub(crate) unsafe fn remote_search_production_session_consistency_policy_summary_row(
    index_relation: pg_sys::Relation,
    requested_epoch: u64,
) -> SpireRemoteProductionConsistencyPolicySummaryRow {
    let consistency_mode = options::current_session_remote_search_consistency_mode_name();
    unsafe {
        remote_search_production_consistency_policy_summary_row(
            index_relation,
            requested_epoch,
            "ec_spire.remote_search_consistency_mode",
            consistency_mode,
        )
    }
}

pub(crate) fn remote_search_production_fault_matrix_rows(
) -> Vec<SpireRemoteProductionFaultMatrixRow> {
    vec![
        production_fault_matrix_row(
            1,
            SPIRE_REMOTE_STATUS_CONSISTENCY_MODE_MISMATCH,
            "consistency_policy",
            SPIRE_REMOTE_EXECUTOR_STEP_CONSISTENCY_POLICY,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CONSISTENCY_MODE_MISMATCH,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CONSISTENCY_MODE_MISMATCH,
            "do not dispatch when the requested consistency mode differs from the published active epoch policy",
        ),
        production_fault_matrix_row(
            2,
            SPIRE_REMOTE_STATUS_EXECUTOR_OVERLOAD,
            "executor_governance",
            SPIRE_REMOTE_EXECUTOR_STEP_GOVERNANCE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_EXECUTOR_OVERLOAD,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "release saturated global or per-node governance slots before strict search; degraded mode may skip only that node",
        ),
        production_fault_matrix_row(
            3,
            SPIRE_REMOTE_STATUS_REQUIRES_SECRET,
            "conninfo_secret",
            SPIRE_REMOTE_EXECUTOR_STEP_SECRET,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "resolve the conninfo secret before strict search; degraded mode may skip only that node",
        ),
        production_fault_matrix_row(
            4,
            SPIRE_REMOTE_PRODUCTION_TRANSPORT_CONNINFO_PARSE_FAILED,
            "transport",
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "fix sanitized conninfo syntax or skip the affected remote under degraded mode",
        ),
        production_fault_matrix_row(
            5,
            SPIRE_REMOTE_PRODUCTION_TRANSPORT_CONNECT_FAILED,
            "transport",
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "treat connect, authentication, certificate, and connect-timeout failures as sanitized transport failures",
        ),
        production_fault_matrix_row(
            6,
            SPIRE_REMOTE_PRODUCTION_TRANSPORT_STATEMENT_TIMEOUT_SETUP_FAILED,
            "transport",
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "do not run an uncapped remote query when remote statement_timeout setup fails",
        ),
        production_fault_matrix_row(
            7,
            SPIRE_REMOTE_PRODUCTION_REMOTE_STATEMENT_TIMEOUT,
            "transport",
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "remote-owned statement timeout is a remote-node failure, not a local cancellation",
        ),
        production_fault_matrix_row(
            8,
            SPIRE_REMOTE_PRODUCTION_REMOTE_BACKEND_TERMINATED,
            "transport",
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "backend termination or connection reset must not be merged as an empty successful result",
        ),
        production_fault_matrix_row(
            9,
            SPIRE_REMOTE_PRODUCTION_REMOTE_QUERY_CANCELLED,
            "transport",
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "remote query cancellation is remote-owned unless the local adapter reports a local cancellation category",
        ),
        production_fault_matrix_row(
            10,
            SPIRE_REMOTE_PRODUCTION_LOCAL_QUERY_CANCELLED,
            "local_cancellation",
            SPIRE_REMOTE_EXECUTOR_STEP_CANCELLATION,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "local query cancellation is query-wide and clears all retained candidate batches in every consistency mode",
        ),
        production_fault_matrix_row(
            11,
            SPIRE_REMOTE_PRODUCTION_LOCAL_STATEMENT_TIMEOUT,
            "local_cancellation",
            SPIRE_REMOTE_EXECUTOR_STEP_CANCELLATION,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "local statement timeout is query-wide and distinct from remote_statement_timeout",
        ),
        production_fault_matrix_row(
            12,
            SPIRE_REMOTE_PRODUCTION_CANDIDATE_DECODE_FAILED,
            "candidate_receive",
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "malformed compact candidate rows cannot enter merge in strict mode",
        ),
        production_fault_matrix_row(
            13,
            SPIRE_REMOTE_PRODUCTION_CANDIDATE_VALIDATION_FAILED,
            "candidate_receive",
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "candidate batch validation failures preserve the exact category before merge",
        ),
        production_fault_matrix_row(
            14,
            SPIRE_REMOTE_STATUS_ENDPOINT_IDENTITY_MISMATCH,
            "endpoint_identity",
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "descriptor, index, quantizer, opclass, storage, and fingerprint mismatches are identity failures",
        ),
        production_fault_matrix_row(
            15,
            SPIRE_REMOTE_PRODUCTION_PROTOCOL_VERSION_MISMATCH,
            "endpoint_identity",
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "protocol version skew must be rejected before candidate merge",
        ),
        production_fault_matrix_row(
            16,
            SPIRE_REMOTE_STATUS_INCOMPATIBLE_EXTENSION_VERSION,
            "descriptor_version",
            SPIRE_REMOTE_EXECUTOR_STEP_EXTENSION_VERSION,
            "fail_closed",
            SPIRE_REMOTE_STATUS_INCOMPATIBLE_EXTENSION_VERSION,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "descriptor-advertised extension skew blocks strict dispatch planning",
        ),
        production_fault_matrix_row(
            17,
            SPIRE_REMOTE_PRODUCTION_EXTENSION_VERSION_MISMATCH,
            "endpoint_identity",
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "live endpoint extension skew invalidates cached endpoint identity",
        ),
        production_fault_matrix_row(
            18,
            SPIRE_REMOTE_STATUS_STALE_EPOCH,
            "epoch_window",
            SPIRE_REMOTE_EXECUTOR_STEP_EPOCH_WINDOW,
            "fail_closed",
            SPIRE_REMOTE_STATUS_STALE_EPOCH,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "stale descriptor epoch cannot satisfy strict fanout and is a named degraded skip",
        ),
        production_fault_matrix_row(
            19,
            SPIRE_REMOTE_PRODUCTION_SERVED_EPOCH_MISMATCH,
            "candidate_receive",
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "served epoch mismatches are rejected after receive instead of folded into generic validation",
        ),
        production_fault_matrix_row(
            20,
            SPIRE_REMOTE_PRODUCTION_REQUESTED_EPOCH_MISMATCH,
            "consistency_policy",
            SPIRE_REMOTE_EXECUTOR_STEP_CONSISTENCY_POLICY,
            "fail_closed",
            SPIRE_REMOTE_PRODUCTION_REQUESTED_EPOCH_MISMATCH,
            "fail_closed",
            SPIRE_REMOTE_PRODUCTION_REQUESTED_EPOCH_MISMATCH,
            "requested epoch mismatch is a coordinator request error, not a degraded remote skip",
        ),
        production_fault_matrix_row(
            21,
            SPIRE_REMOTE_PRODUCTION_REMOTE_INDEX_UNAVAILABLE,
            "endpoint_identity",
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "missing remote index or regclass resolution failure cannot be treated as an empty batch",
        ),
        production_fault_matrix_row(
            22,
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_RESOLUTION_FAILED,
            "remote_heap_resolution",
            SPIRE_REMOTE_EXECUTOR_STEP_REMOTE_HEAP_RESOLUTION,
            "fail_closed",
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_RESOLUTION_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "remote heap query failure blocks final SQL rows unless degraded mode skips that origin node",
        ),
        production_fault_matrix_row(
            23,
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_ROW_MISSING,
            "remote_heap_resolution",
            SPIRE_REMOTE_EXECUTOR_STEP_REMOTE_HEAP_RESOLUTION,
            "fail_closed",
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_ROW_MISSING,
            "skip_candidate",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "missing origin heap rows must be counted and either fail strict or be explicitly skipped",
        ),
        production_fault_matrix_row(
            24,
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_ROW_DEAD,
            "remote_heap_resolution",
            SPIRE_REMOTE_EXECUTOR_STEP_REMOTE_HEAP_RESOLUTION,
            "fail_closed",
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_ROW_DEAD,
            "skip_candidate",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "dead origin heap rows must be counted and must not be returned as visible SQL rows",
        ),
        production_fault_matrix_row(
            25,
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_ROW_STALE,
            "remote_heap_resolution",
            SPIRE_REMOTE_EXECUTOR_STEP_REMOTE_HEAP_RESOLUTION,
            "fail_closed",
            SPIRE_REMOTE_PRODUCTION_REMOTE_HEAP_ROW_STALE,
            "skip_candidate",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "stale origin row locators must be rejected or explicitly skipped with diagnostics",
        ),
        production_fault_matrix_row(
            26,
            SPIRE_REMOTE_PRODUCTION_TRANSPORT_REMOTE_QUERY_FAILED,
            "transport",
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "uncategorized remote query failures, including remote OOM, cannot enter merge as empty results",
        ),
        production_fault_matrix_row(
            27,
            SPIRE_REMOTE_STATUS_TUPLE_TRANSPORT_RETIRED,
            "tuple_transport",
            SPIRE_REMOTE_EXECUTOR_STEP_CUSTOM_SCAN_TUPLE_DELIVERY,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            SPIRE_REMOTE_TUPLE_TRANSPORT_RETIRED_HINT,
        ),
        production_fault_matrix_row(
            28,
            SPIRE_REMOTE_STATUS_REMOTE_PAYLOAD_TOO_LARGE,
            "remote_payload",
            SPIRE_REMOTE_EXECUTOR_STEP_CUSTOM_SCAN_TUPLE_DELIVERY,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            SPIRE_REMOTE_PAYLOAD_TOO_LARGE_HINT,
        ),
    ]
}

fn production_fault_matrix_row(
    fault_ordinal: u64,
    failure_category: &'static str,
    fault_scope: &'static str,
    next_executor_step: &'static str,
    strict_action: &'static str,
    strict_status: &'static str,
    degraded_action: &'static str,
    degraded_status: &'static str,
    recommendation: &'static str,
) -> SpireRemoteProductionFaultMatrixRow {
    SpireRemoteProductionFaultMatrixRow {
        fault_ordinal,
        failure_category,
        fault_scope,
        next_executor_step,
        strict_action,
        strict_status,
        degraded_action,
        degraded_status,
        recommendation,
    }
}

pub(crate) fn remote_search_stage_e_fault_matrix_rows() -> Vec<SpireRemoteStageEFaultMatrixRow> {
    vec![
        stage_e_fault_matrix_row(
            1,
            "epoch_mismatch",
            "remote_epoch_window",
            SPIRE_REMOTE_STATUS_STALE_EPOCH,
            SPIRE_REMOTE_EXECUTOR_STEP_EPOCH_WINDOW,
            "fail_closed",
            SPIRE_REMOTE_STATUS_STALE_EPOCH,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "strict_failed_dispatch_count+1; degraded_skipped_dispatch_count+1",
            "one coordinator plus two remotes; stale remote advertises served epoch outside requested retained window",
        ),
        stage_e_fault_matrix_row(
            2,
            "version_skew",
            "remote_extension_version",
            SPIRE_REMOTE_STATUS_INCOMPATIBLE_EXTENSION_VERSION,
            SPIRE_REMOTE_EXECUTOR_STEP_EXTENSION_VERSION,
            "fail_closed",
            SPIRE_REMOTE_STATUS_INCOMPATIBLE_EXTENSION_VERSION,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "strict_failed_dispatch_count+1; degraded_skipped_dispatch_count+1",
            "remote descriptor advertises incompatible extension version before dispatch opens sockets",
        ),
        stage_e_fault_matrix_row(
            3,
            "fingerprint_mismatch",
            "endpoint_identity",
            SPIRE_REMOTE_STATUS_ENDPOINT_IDENTITY_MISMATCH,
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "identity_cache_invalidations+1; degraded_skipped_dispatch_count+1",
            "live endpoint fingerprint differs from descriptor remote_index_identity",
        ),
        stage_e_fault_matrix_row(
            4,
            "connection_reset_mid_batch",
            "transport",
            SPIRE_REMOTE_PRODUCTION_REMOTE_BACKEND_TERMINATED,
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "transport_failed_dispatch_count+1; degraded_skipped_dispatch_count+1",
            "remote connection closes while an in-flight production request is receiving rows",
        ),
        stage_e_fault_matrix_row(
            5,
            "remote_backend_termination",
            "transport",
            SPIRE_REMOTE_PRODUCTION_REMOTE_BACKEND_TERMINATED,
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "transport_failed_dispatch_count+1; degraded_skipped_dispatch_count+1",
            "remote backend is terminated before it can return a validated batch",
        ),
        stage_e_fault_matrix_row(
            6,
            "remote_statement_timeout",
            "transport",
            SPIRE_REMOTE_PRODUCTION_REMOTE_STATEMENT_TIMEOUT,
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "remote_statement_timeout_count+1; degraded_skipped_dispatch_count+1",
            "remote statement_timeout fires on one remote while other ready remotes can still complete",
        ),
        stage_e_fault_matrix_row(
            7,
            "local_statement_timeout",
            "local_cancellation",
            SPIRE_REMOTE_PRODUCTION_LOCAL_STATEMENT_TIMEOUT,
            SPIRE_REMOTE_EXECUTOR_STEP_CANCELLATION,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "cancelled_dispatch_count=fanout; retained_candidate_batch_count=0",
            "coordinator statement_timeout cancels every in-flight remote and releases governance permits",
        ),
        stage_e_fault_matrix_row(
            8,
            "local_cancel",
            "local_cancellation",
            SPIRE_REMOTE_PRODUCTION_LOCAL_QUERY_CANCELLED,
            SPIRE_REMOTE_EXECUTOR_STEP_CANCELLATION,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "cancel_query",
            SPIRE_REMOTE_STATUS_EXECUTOR_CANCELLED,
            "cancelled_dispatch_count=fanout; retained_candidate_batch_count=0",
            "client query cancel interrupts every in-flight remote and releases governance permits",
        ),
        stage_e_fault_matrix_row(
            9,
            "simulated_network_partition",
            "transport",
            SPIRE_REMOTE_PRODUCTION_TRANSPORT_CONNECT_FAILED,
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "connect_failed_count+1; degraded_skipped_dispatch_count+1",
            "one remote conninfo is unreachable while at least one other remote remains ready",
        ),
        stage_e_fault_matrix_row(
            10,
            "remote_oom",
            "transport",
            SPIRE_REMOTE_PRODUCTION_TRANSPORT_REMOTE_QUERY_FAILED,
            SPIRE_REMOTE_EXECUTOR_STEP_PRODUCTION_TRANSPORT,
            "fail_closed",
            SPIRE_REMOTE_STATUS_PRODUCTION_TRANSPORT_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "remote_query_failed_count+1; degraded_skipped_dispatch_count+1",
            "remote returns a sanitized out-of-memory query failure without leaking raw remote error text",
        ),
        stage_e_fault_matrix_row(
            11,
            "missing_or_reindexed_remote_index",
            "endpoint_identity",
            SPIRE_REMOTE_PRODUCTION_REMOTE_INDEX_UNAVAILABLE,
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            "remote_index_unavailable_count+1; degraded_skipped_dispatch_count+1",
            "remote index is dropped, renamed, or rebuilt after planning but before receive",
        ),
    ]
}

fn stage_e_fault_matrix_row(
    fault_ordinal: u64,
    fault_case: &'static str,
    fixture_scope: &'static str,
    failure_category: &'static str,
    next_executor_step: &'static str,
    strict_action: &'static str,
    strict_status: &'static str,
    degraded_action: &'static str,
    degraded_status: &'static str,
    counter_delta: &'static str,
    required_evidence: &'static str,
) -> SpireRemoteStageEFaultMatrixRow {
    SpireRemoteStageEFaultMatrixRow {
        fault_ordinal,
        fault_case,
        fixture_scope,
        failure_category,
        next_executor_step,
        strict_action,
        strict_status,
        degraded_action,
        degraded_status,
        counter_delta,
        required_evidence,
    }
}

pub(crate) fn remote_search_stage_e_lifecycle_matrix_rows(
) -> Vec<SpireRemoteStageELifecycleMatrixRow> {
    vec![
        stage_e_lifecycle_matrix_row(
            1,
            "drop_remote_index_before_fanout",
            "DROP INDEX",
            "before_fanout_planning",
            "remote_index_regclass",
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            SPIRE_REMOTE_PRODUCTION_REMOTE_INDEX_UNAVAILABLE,
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "planner or receive path resolves remote_index_regclass and records remote_index_unavailable instead of treating the node as empty",
        ),
        stage_e_lifecycle_matrix_row(
            2,
            "drop_remote_index_in_flight",
            "DROP INDEX",
            "after_fanout_before_receive",
            "remote_index_regclass",
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            SPIRE_REMOTE_PRODUCTION_REMOTE_INDEX_UNAVAILABLE,
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "in-flight receive validates the remote index still exists before accepting candidate rows",
        ),
        stage_e_lifecycle_matrix_row(
            3,
            "reindex_remote_index_before_fanout",
            "REINDEX INDEX CONCURRENTLY",
            "before_fanout_planning",
            "remote_index_identity",
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            SPIRE_REMOTE_STATUS_ENDPOINT_IDENTITY_MISMATCH,
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "descriptor remote_index_identity must be refreshed after reindex before dispatch is considered ready",
        ),
        stage_e_lifecycle_matrix_row(
            4,
            "reindex_remote_index_in_flight",
            "REINDEX INDEX CONCURRENTLY",
            "after_fanout_before_receive",
            "remote_index_identity",
            "fail_closed",
            SPIRE_REMOTE_STATUS_CANDIDATE_RECEIVE_FAILED,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            SPIRE_REMOTE_STATUS_ENDPOINT_IDENTITY_MISMATCH,
            SPIRE_REMOTE_EXECUTOR_STEP_COMPACT_CANDIDATE_RECEIVE,
            "candidate receive compares live endpoint identity with the planned descriptor identity before merge",
        ),
        stage_e_lifecycle_matrix_row(
            5,
            "create_index_concurrently_new_descriptor",
            "CREATE INDEX CONCURRENTLY",
            "during_existing_fanout",
            "remote_node_descriptor_generation",
            "defer_new_descriptor",
            SPIRE_REMOTE_STATUS_READY,
            "defer_new_descriptor",
            SPIRE_REMOTE_STATUS_READY,
            "descriptor_generation_snapshot",
            SPIRE_REMOTE_EXECUTOR_STEP_DESCRIPTOR,
            "new remote indexes are ignored by the already-planned fanout until descriptor generation advances for a later query",
        ),
        stage_e_lifecycle_matrix_row(
            6,
            "create_index_concurrently_missing_descriptor",
            "CREATE INDEX CONCURRENTLY",
            "before_descriptor_registration",
            "remote_node_descriptor",
            "fail_closed",
            SPIRE_REMOTE_STATUS_REQUIRES_DESCRIPTOR,
            "skip_node",
            SPIRE_REMOTE_STATUS_DEGRADED_SKIPPED,
            SPIRE_REMOTE_STATUS_REQUIRES_DESCRIPTOR,
            SPIRE_REMOTE_EXECUTOR_STEP_DESCRIPTOR,
            "a newly-created remote index is not used until the coordinator has an active descriptor and identity binding",
        ),
    ]
}

fn stage_e_lifecycle_matrix_row(
    lifecycle_ordinal: u64,
    lifecycle_case: &'static str,
    ddl_event: &'static str,
    fanout_timing: &'static str,
    affected_surface: &'static str,
    strict_action: &'static str,
    strict_status: &'static str,
    degraded_action: &'static str,
    degraded_status: &'static str,
    required_detection: &'static str,
    next_executor_step: &'static str,
    required_evidence: &'static str,
) -> SpireRemoteStageELifecycleMatrixRow {
    SpireRemoteStageELifecycleMatrixRow {
        lifecycle_ordinal,
        lifecycle_case,
        ddl_event,
        fanout_timing,
        affected_surface,
        strict_action,
        strict_status,
        degraded_action,
        degraded_status,
        required_detection,
        next_executor_step,
        required_evidence,
    }
}

